language: python3
sudo: enabled
python:
    - 3.6
before_install:
    - sudo apt-get install python3-pip
install:
    - pip3 install flake8 --user
script:
    - flake8
    - /bin/bash install.sh
    - python welcome_screen.py .

