sudo: enabled
env:
    - SHELL_TYPE=fish
    - SHELL_TYPE=bash
    - SHELL_TYPE=powershell
language: python3
python:
    - "3.6"
before_install:
    - sudo apt-get install -y fish
    - wget https://github.com/PowerShell/PowerShell/releases/download/v6.1.0/powershell_6.1.0-1.ubuntu.14.04_amd64.deb
    - sudo dpkg -i powershell_6.1.0-1.ubuntu.14.04_amd64.deb
    - sudo apt-get install -f
install:
    - pyenv global system 3.6
    - pip3.6 install flake8 pytest --user
script:
    - flake8
    - pytest
    - /bin/bash install.sh
    - if [ $SHELL_TYPE = 'fish' ]; then fish -c 'exit'; fi
    - if [ $SHELL_TYPE = 'bash' ]; then bash -c 'exit'; fi
    - if [ $SHELL_TYPE = 'powershell' ]; then pwsh -c 'exit'; fi

