language: python3
sudo: enabled
python:
    - 3.6
before_install:
    - sudo apt-get install python3-pip
install:
    - pip3 install flake8
script:
    - flake8
    - /bin/bash install.sh
    - python3 welcome_screen.py .

