language: python3
sudo: enabled
python:
    - "3.6"
install:
    - pyenv global system 3.6
    - pip3.6 install flake8 --user
script:
    - flake8
    - /bin/bash install.sh
    - python3.6 welcome_screen.py .

