os: linux
dist: xenial
language: python
python: "3.7"
jobs:
    include:
        - name: "Fish"
          env: SHELL_TYPE=fish
          before_install:
            - sudo apt-add-repository -y ppa:fish-shell/release-2
            - sudo add-apt-repository -y ppa:deadsnakes/ppa
            - sudo apt-get update
            - sudo apt-get install -y fish python3.7 golang-go
            - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
          install:
            - pyenv global system 3.7.1
            - /bin/bash install.sh
          script:
            - fish -c 'exit'
        - name: "Bash"
          env: SHELL_TYPE=bash
          before_install:
             - sudo add-apt-repository -y ppa:deadsnakes/ppa
             - sudo apt-get update
             - sudo apt-get install -y python3.7 golang-go
             - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
          install:
            - pyenv global system 3.7.1
            - /bin/bash install.sh
          script:
            - bash -c 'exit'
        - name: "PowerShell"
          env: SHELL_TYPE=powershell
          before_install:
             - sudo apt-get update
             - wget https://github.com/PowerShell/PowerShell/releases/download/v7.0.2/powershell-lts_7.0.2-1.ubuntu.16.04_amd64.deb
             - sudo dpkg -i powershell-lts_7.0.2-1.ubuntu.16.04_amd64.deb || true
             - sudo apt-get install -f
             - sudo add-apt-repository -y ppa:deadsnakes/ppa
             - sudo apt-get update
             - sudo apt-get install -y python3.7 golang-go python3-gdbm python3.7-gdbm
             - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
          install:
            - pyenv global system 3.7.1
            - pwsh install.ps1
          script:
            - pwsh -c 'exit'
        - name: "Zsh"
          env: SHELL_TYPE=zsh
          before_install:
             - sudo add-apt-repository -y ppa:deadsnakes/ppa
             - sudo apt-get update
             - sudo apt-get install -y python3.7 zsh golang-go
             - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
          install:
            - pyenv global system 3.7.1
            - /bin/bash install.sh
          script:
            - zsh -c 'exit'
        - name: "Xonsh"
          env: SHELL_TYPE=xonsh
          before_install:
            - sudo add-apt-repository -y ppa:deadsnakes/ppa
            - sudo apt-get update
            - sudo apt-get install -y python3.7 golang-go python3-gdbm python3.7-gdbm
            - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
          install:
            - pyenv global system 3.7.1
            - pip install pygments xonsh
            - /bin/bash install.sh
          script:
            - xonsh -c 'exit'

