sudo: enabled
language: python3
python: "3.6"
matrix:
    include: 
        - name: "Fish"
          env: SHELL_TYPE=fish
          before_install:
            - sudo apt-add-repository -y ppa:fish-shell/release-2
            - sudo add-apt-repository -y ppa:deadsnakes/ppa
            - sudo apt-get update
            - sudo apt-get install -y fish python3.6
            - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
          install: 
            - pyenv global system 3.6
            - pip3.6 install flake8 pytest --user
            - /bin/bash install.sh
          script:
            - flake8
            - pytest
            - fish -c 'exit'
        - name: "Bash"
          env: SHELL_TYPE=bash
          before_install:
             - sudo add-apt-repository -y ppa:deadsnakes/ppa
             - sudo apt-get update
             - sudo apt-get install -y python3.6
             - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 
          install:
            - pyenv global system 3.6
            - pip3.6 install flake8 pytest --user
            - /bin/bash install.sh
          script:
            - flake8
            - pytest
            - bash -c 'exit'
        - name: "PowerShell"
          env: SHELL_TYPE=powershell
          before_install:
             - wget https://github.com/PowerShell/PowerShell/releases/download/v6.1.0/powershell_6.1.0-1.ubuntu.14.04_amd64.deb
             - sudo dpkg -i powershell_6.1.0-1.ubuntu.14.04_amd64.deb || true
             - sudo apt-get install -f
             - sudo add-apt-repository -y ppa:deadsnakes/ppa
             - sudo apt-get update
             - sudo apt-get install -y python3.6
             - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 
          install:
            - pyenv global system 3.6
            - pip3.6 install flake8 pytest --user
            - pwsh install.ps1
          script:
            - flake8
            - pytest
            - pwsh -c 'exit'

