sudo: enabled
language: python
python: "3.6"
before_install:
    - sudo apt-get install -y fish
    - wget https://github.com/PowerShell/PowerShell/releases/download/v6.1.0/powershell_6.1.0-1.ubuntu.14.04_amd64.deb
    - sudo dpkg -i powershell_6.1.0-1.ubuntu.14.04_amd64.deb
    - sudo apt-get install -f
install:
    - pyenv global system 3.6
    - pip3.6 install flake8 pytest --user
matrix:
    include: 
        - name: "Fish"
          env: SHELL_TYPE=fish
          script:
            - flake8
            - pytest
            - /bin/bash install.sh
            - fish -c 'exit'
        - name: "Bash"
          env: SHELL_TYPE=bash
          script:
            - flake8
            - pytest
            - /bin/bash install.sh
            - bash -c 'exit'
        - name: "PowerShell"
          env: SHELL_TYPE=powershell
          script:
            - flake8
            - pytest
            - /bin/bash install.sh
            - pwsh -c 'exit'

