#!/bin/bash
function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

if valid_ip $1; then
    curl ipinfo.io/$1
    exit 0
fi

# Resolve hostname first
HOSTNAME_IP=$(dig +short $1 | tail -1)
if [[ $? != 0 || $HOSTNAME_IP == '' ]]; then
    echo "Could not resolve $1 to a hostname!"
    exit -1
fi

curl ipinfo.io/$HOSTNAME_IP
